config/routes.rb
Onlinefighter::Application.routes.draw do

  devise_for :users,  path_names: {sign_in: "login", sign_out: "logout"},
                      controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root :to => 'application#welcome'
  match 'characters/new' => 'characters#new'
  match 'characters/dashboard' => 'characters#dashboard'
  match 'characters/choose' => 'characters#choose', :via => :post
  match 'services/create' => 'services#create', :via => :post
  match 'items/equip' => 'items#equip', :via => :post
  match 'battles/create' => 'battles#create', :via => :post
  match 'characters/destroy' => 'characters#destroy', :via => :post
  match 'services/destroy' => 'services#destroy', :via => :post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onlinefighter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='container'>

    <div id="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <% if current_user.character.present? %>
          <%= link_to "Dashboard", characters_dashboard_path %> |
        <% else %>
          <%= link_to "New character", characters_new_path %> |
        <% end %>
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path %> |
        <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %> |
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %> |
        <%= link_to "Sign in with Vkontakte", user_omniauth_authorize_path(:vkontakte) %> |
      <% end %>
    </div>

    <div id="notifications">
      <% if alert %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= alert %>
        </div>
      <% end %>

      <% if notice %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </div>
      <% end %>
    </div>

    <div id="page_content">
      <%= yield %>
    </div>

  </div>
</body>
</html>